version: "2.4"

services:
  sunpy-kamodo-stable: # does not actually work
    image: apembroke/kamodo-sunpy
    ports:
      - "8888:8888"
    platform: linux/amd64
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /
  sunpy-kamodo-dev:
    image: ensemble/sunpy
    ports:
      - "8889:8888"
    build: 
      context: .
      dockerfile: dockerfiles/sunpyKamodo.Dockerfile
    platform: linux/amd64
    command:
      - jupyter
      - notebook
      - /kamodo-sunpy
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo-sunpy
    working_dir: /kamodo-sunpy
